<?php
$smtp_host ='smtp.privateemail.com';
$smtp_port ='465';
$smtp_secure='ssl';
$smtp_user='sales@kenique.biz';
$smtp_psw='Biz@360';


// mis reports start  /////////////////////////////////////////////////////////////////////////////

$mis_from = "sales@kenique.biz";
$mis_path='misreport/';  // attachement files folder


$mis_to = "sm@kenique.biz";

$mis_cc = "sharmamalladi@gmail.com";
$mis_subject = 'MedBot : Revenue Report As on';
$mis_message='Dear All,Please Find the email';
//$mis_footer='This is the email generated by MedBot';


?>